// flow-typed signature: 6f049899b8baa3ad0206c4767d72b947
// flow-typed version: <<STUB>>/dotenv-expand_v4.0.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv-expand'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dotenv-expand' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dotenv-expand/lib/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dotenv-expand/lib/main.js' {
  declare module.exports: $Exports<'dotenv-expand/lib/main'>;
}
