// flow-typed signature: 1f7570550bb82b6104790430d193d432
// flow-typed version: <<STUB>>/ghooks_v^2.0.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ghooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ghooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ghooks/lib/hook.template' {
  declare module.exports: any;
}

declare module 'ghooks/lib/install' {
  declare module.exports: any;
}

declare module 'ghooks/lib/runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ghooks/lib/hook.template.js' {
  declare module.exports: $Exports<'ghooks/lib/hook.template'>;
}
declare module 'ghooks/lib/install.js' {
  declare module.exports: $Exports<'ghooks/lib/install'>;
}
declare module 'ghooks/lib/runner.js' {
  declare module.exports: $Exports<'ghooks/lib/runner'>;
}
